<div style="background:#0011E3;color:#FFF;font-size:18px;height:80px;line-height:80px;text-align:center;">
    ABOUT US
</div>
<div style="width:100%;background:#161B5D;">
<div style="padding:50px 0 0 0;">
    <div style="background:#141958;overflow:hidden;position:relative;box-shadow:0 0 15px rgba(0,0,0,.2);height:600px;margin:0 auto;width:1100px;">
        <div style="position:absolute;left:0;height:80px;width:420px;top:80px;background:#1f2380;box-shadow:0 0 15px rgba(0,0,0,.1);">
            <img src="/img/about/t0.png" style="position:absolute;left:60px;top:-25px;" />
        </div>
        <div style="position:absolute;left:0;top:160px;width:550px;height:380px;background:#171b60;box-shadow:0 0 15px rgba(0,0,0,.1);">
            <img src="/img/about/t1.png" style="position:absolute;left:60px;top:35px;" />
            <img src="/img/about/t2.jpg" style="position:absolute;right:60px;bottom:35px;" />
        </div>
        <img src="/img/about/t3.png" style="position:absolute;right:60px;bottom:60px;" />
    </div>
</div>

<div style="padding:50px 0 50px 0;">
    <div style="height:700px;margin:0 auto;width:1100px;background:url(/img/about/t5.jpg) center center no-repeat;background-size: contain;position:relative;">
        <img src="/img/about/t3.png" class="mgdicovr" />
    </div>
</div>

<div style="height:650px;background:#141958;position:relative;">
    <div style="background:url(/img/about/t4.jpg) center center no-repeat;background-size:contain;width:360px;height:180px;position:absolute;left:50%;margin-left:-180px;top:50%;margin-top:-90px;"></div>
</div>

<div style="background:#171B60;position:relative;padding-top:40px;">
    <div style="width:1100px;margin:auto;padding-top:80px;padding-bottom:30px;">
        <img src="/img/about/t3.png" class="mgdicovr">
        <div style="background:url(/img/about/t9.jpg) left center no-repeat;background-size: cover;height:130px;box-shadow:0 0 15px rgba(0,0,0,.1);">

        </div>
        <div style="background:#141958;padding:30px 70px;box-shadow:0 0 15px rgba(0,0,0,.2);">
            <div style="width:50%;float:left;color:#FFF;line-height:28px;">
                <div style="margin-bottom:25px;">简称VR設計，是一间富有创造力，具有国际视野的新锐设计公司。由香港，深圳，广州，珠海的资深设计师组成的设计团队，坚持【以视觉与策略的力量去净化品牌细胞，从内至外的再生】为不同领域的品牌做全面的分析，以敏锐的洞察力和多年丰富的经验为品作准确定位，创意策划，品牌文化，品牌形象的完整方案，成功的以设计带动品牌发展，因发展给品牌带来商业价值的双赢合作。</div>
                <div style="font-weight:bold;font-size:18px;">Shenzhen VR design Co. Ltd.</div>
                <div style="font-size:12px;line-height:26px;">VR brand design is a creative, cutting-edge design company with a global vision. Design team consisting of senior designer from Hong Kong, Shenzhen Guangzhou, Zhuhai, adhere to the The vision and strategy of the power to evolutionary brand cell regeneration "from the inside to the outside". Brand in the field to do a comprehensive analysis, insight and years of experience as a product. Card for accurate positioning, creative planning, brand image complete program success Design-driven brand development, brand development to the commercial value of win-win cooperation.</div>
            </div>
            <div style="width:50%;float:left;">
                <img src="/img/about/t10.jpg" style="width:92%;float:right;box-shadow: 0 0 10px rgba(0,0,0,.1);" />
            </div>
            <div class="clear"></div>
        </div>
    </div>
</div>

<div style="background:#171B60;position:relative;padding-top:40px;">
    <div style="width:1100px;margin:auto;padding-top:80px;padding-bottom:30px;">
        <img src="/img/about/t3.png" class="mgdicovr">
        <div style="background:#141958;padding:30px 70px;box-shadow:0 0 15px rgba(0,0,0,.2);">
            <div style="width:50%;float:left;color:#FFF;line-height:28px;">
                <div style="margin-bottom:25px;padding-right:20px;">简称VR设计，是一间富有创造力，具有国际视野的新锐设计公司。由香港，深圳，广州，珠海的资深设计师组成的设计团队，坚持【以视觉与策略的力量去净化品牌细胞，从内至外的再生】为不同领域的品牌做全面的分析，以敏锐的洞察力和多年丰富的经验为品作准确定位，创意策划，品牌文化，品牌形象的完整方案，成功的以设计带动品牌发展，因发展给品牌带来商业价值的双赢合作。</div>
            </div>
            <div style="width:50%;float:left;color:#FFF;line-height:28px;">
                <div style="margin-bottom:25px;padding-left:20px;">VR brand design is a creative, cutting-edge design company with a global vision. Design team consisting of senior designer from Hong Kong, Shenzhen Guangzhou, Zhuhai, adhere to the The vision and strategy of the power to evolutionary brand cell regeneration "from the inside to the outside". Brand in the field</div>
            </div>
            <div class="clear"></div>
            <img src="/img/about/t11.jpg" style="width:100%" />
        </div>
    </div>

</div>

<div class="ionc-m">
    <div class="ionc-mie">
        <img src="/img/about/t7.png" class="ionc-bigdna"/>
        <img src="/img/about/t3.png" class="mgdicovr" />
        <div class="ionc_itm01">
            <div class="ionc_itm01_wp">
                <div class="ionc-sity">品牌视觉进化式</div>
                <div class="bd">品牌是生命体</div>
                <div>我们认为，品牌是人类创造出来的价值生命体。如同万物，有细胞有结构有意识等等。</div>
                <div>品牌的文化理念，就像生物的DNA基因， 是品牌成形的信息依据和决定物质。</div>
                <div>品牌的视觉形象，则像生物的结构形态，从眼耳口鼻至四肢角羽，是最直观的最真实的视觉呈现。</div>
                <div>品牌的视觉推广，正如生物的行为能力，不管是飞天遁地还是言谈举止，都是传播并放大自身特点的动作。</div>
            </div>
        </div>
        <div class="ionc_itm01">
            <div class="ionc_itm01_wp">
                <div class="bd">为什么要进化式</div>
                <div>大自然适者生存，生物想要存活得更好，必须进化。品牌亦是如此。</div>
                <div>当今社会兴起品牌日益增多，淘汰率亦是正比。</div>
                <div>不能跟上时代趋势和落后品牌意识的企业必定成为牺牲者。</div>
                <div>为了品牌可以充分迎接时代挑战并出众发展，需要我们的视觉进化式。</div>
            </div>
        </div>
        <div class="ionc_itm01">
            <div class="ionc_itm01_wp last">
                <div>视觉进化式</div>
                <div>从品牌DNA开始做准备鲜明的定位和宏观有价值的规划，塑造文化积淀，让消费者形成强烈的品牌忠诚度，为品牌进化战略的成功实施提供强有力的保障。</div>
                <div>再落实于品牌视觉形象上的进化，结合品牌属性及需求，以新锐视觉手法和有效策略图划注入到设计中，而脱离同行品牌的复制化的恶性竞争，实现优越形象的进化目的。</div>
                <div>从独特角度去发掘品牌自身价值，并以巧妙的创意加以推广，带动品牌与消费者在感情上达成一种共鸣。</div>
                <div>品牌的视觉推广，正如生物的行为能力，不管是飞天遁地还是言谈举止，都是传播并放大自身特点的动作。</div>
            </div>
        </div>
        <div class="clear-30"></div>
    </div>

</div>

<div class="ionc-m">
    <div class="ionc-mie">
        <img src="/img/about/t7.png" class="ionc-bigdna"/>
        <img src="/img/about/t3.png" class="mgdicovr" />
        <div class="ionc_itm01">
            <div class="ionc_itm01_wp">
                <div class="ionc-sity">Evolutionary brand vision</div>
                <div class="bd">Brand is the life of the body</div>
                <div>We believe that the brand of value of human life form created. Like all things, there are so conscious cell structure.</div>
                <div>Cultural concept of the brand, just like DNA modified organisms, information and decisions based on brand forming substance.</div>
                <div>The brand's visual identify, is like morphology creatures, from the eyes, ears, norse and mouth to the limbs angle feathers, is the most intutitive of the most realistic.</div>
                <div>Visual brand promotion, as the biological capacity, whether or fly or manners, are spread and amplify its own characteristics action.</div>
            </div>
        </div>
        <div class="ionc_itm01">
            <div class="ionc_itm01_wp">
                <div style="font-weight:bold;">为什么要进化式</div>
                <div>大自然适者生存，生物想要存活得更好，必须进化。品牌亦是如此。</div>
                <div>当今社会兴起品牌日益增多，淘汰率亦是正比。</div>
                <div>不能跟上时代趋势和落后品牌意识的企业必定成为牺牲者。</div>
                <div>为了品牌可以充分迎接时代挑战并出众发展，需要我们的视觉进化式。</div>
            </div>
        </div>
        <div class="ionc_itm01">
            <div class="ionc_itm01_wp last">
                <div>视觉进化式</div>
                <div>从品牌DNA开始做准备鲜明的定位和宏观有价值的规划，塑造文化积淀，让消费者形成强烈的品牌忠诚度，为品牌进化战略的成功实施提供强有力的保障。</div>
                <div>再落实于品牌视觉形象上的进化，结合品牌属性及需求，以新锐视觉手法和有效策略图划注入到设计中，而脱离同行品牌的复制化的恶性竞争，实现优越形象的进化目的。</div>
                <div>从独特角度去发掘品牌自身价值，并以巧妙的创意加以推广，带动品牌与消费者在感情上达成一种共鸣。</div>
                <div>品牌的视觉推广，正如生物的行为能力，不管是飞天遁地还是言谈举止，都是传播并放大自身特点的动作。</div>
            </div>
        </div>
        <div class="clear-30"></div>
    </div>
</div>

<div style="background:#171B60;position:relative;padding-top:40px;">
    <div style="width:1100px;margin:auto;padding-top:80px;padding-bottom:30px;">
        <img src="/img/about/t3.png" class="mgdicovr">
        <div>

            <div class="mgo_itm">
                <div class="weno cs1"></div>
                <div class="meeno">
                    <div class="metii">
                        全新建立的品牌
                    </div>
                    <div class="mxeit">
                        品 牌 创 造
                    </div>
                </div>
                <div class="soebim">
                    重视前期品牌建立&nbsp;&nbsp;赢在起点
                </div>
                <div class="clear"></div>
            </div>

            <div class="mgo_itm">
                <div class="weno cs2"></div>
                <div class="meeno">
                    <div class="metii">
                        已有品牌 战略升级
                    </div>
                    <div class="mxeit">
                        品 牌 进 化
                    </div>
                </div>
                <div class="soebim">
                    品牌需要发展&nbsp;&nbsp;更需要进化
                </div>
                <div class="clear"></div>
            </div>

            <div class="mgo_itm">
                <div class="weno cs3"></div>
                <div class="meeno">
                    <div class="metii">
                        品牌设计 全面拓展
                    </div>
                    <div class="mxeit">
                        品 牌 升 华
                    </div>
                </div>
                <div class="soebim">
                    设计赋予品牌的价值&nbsp;&nbsp;远远超于你想象
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
</div>

<div style="background:#171B60;position:relative;">
    <div style="width:1100px;margin:auto;padding-top:90px;padding-bottom:30px;">
        <img src="/img/about/t3.png" class="mgdicovr"/>
        <div>
            <div class="llnulle">
                <img src="/img/about/t15.jpg" class="iomg" />
                <div class="imoieh">
                    <div class="ttxe">
                        <div>Brand positioning and naming</div>
                        <div>Brand culture comb</div>
                        <div>Brand Concept Design</div>
                        <div>Product planning</div>
                    </div>
                    <div class="mmuei">策略 进化式</div>
                    <div class="ieio">
                        <div>品牌定位及命名</div>
                        <div>品牌文化梳理</div>
                        <div>品牌理念设计</div>
                        <div>产品系列规划</div>
                    </div>
                </div>
            </div>
            <div class="llnulle">
                <img src="/img/about/t16.jpg" class="iomg" />
                <div class="imoieh">
                    <div class="ttxe">
                        <div>Brand logo design</div>
                        <div>Brand VI system</div>
                        <div>Package Design</div>
                        <div>Brochure Design</div>
                    </div>
                    <div class="mmuei">视觉 进化式</div>
                    <div class="ieio">
                        <div>品牌标志设计</div>
                        <div>品牌视觉识别系统</div>
                        <div>包装设计</div>
                        <div>画册设计</div>
                    </div>
                </div>
            </div>
            <div class="llnulle last">
                <img src="/img/about/t17.jpg" class="iomg" />
                <div class="imoieh">
                    <div class="ttxe">
                        <div>Print Ads</div>
                        <div>Web Design</div>
                        <div>Animation</div>
                        <div>TVC micro film</div>
                    </div>
                    <div class="mmuei">推广 进化式</div>
                    <div class="ieio">
                        <div>平面广告</div>
                        <div>网站设计</div>
                        <div>动画制作</div>
                        <div>影视广告 微电影</div>
                    </div>
                </div>
            </div>
            <div class="clear"></div>
        </div>
    </div>

</div>
<style>
    .laglag {
        width:340px;margin-bottom:40px;margin-right:40px;background:#1F2380;box-shadow: 0 2px 8px rgba(0,0,0,.2);float:left;
    }
    .laglag .wp {
        padding:15px 15px 15px 60px;
    }
    .laglag .num {
        font-size:44px;font-weight:bold;font-style: italic;position:absolute;left:-3px;
        top:-8px;
    }
    .laglag .htxt {
        font-size:25px;font-weight: bold;
        margin-bottom:10px;
    }
    .laglag .stxt {
        font-size: 18px;
    }
    .laglag.last {
        margin-right: 0;
    }
    .laglag.dark {
        background:#141958;
    }
    .laglag.double {
        margin-right:0;
        width:720px;
    }
</style>
<div style="background:#12114d;position:relative;margin-top:30px;padding-top:30px;">
    <img src="/img/about/t18.jpg" style="position:absolute;left:0;top:60px;width:40%;"/>
    <div style="color:#FFF;width:1100px;margin:auto;padding-top:160px;padding-bottom:30px;">
        <img src="/img/about/t3.png" class="mgdicovr"/>
        <div>
            <div class="laglag">
                <div class="wp">
                    <div class="num">1</div>
                    <div class="htxt">Communication</div>
                    <div class="stxt">双方沟通  了解需求</div>
                </div>
            </div>
            <div class="laglag dark">
                <div class="wp">
                    <div class="num">2</div>
                    <div class="htxt">Price</div>
                    <div class="stxt">确定设计项目 及 报价</div>
                </div>
            </div>
            <div class="laglag last">
                <div class="wp">
                    <div class="num">3</div>
                    <div class="htxt">Contracts</div>
                    <div class="stxt">签订合同</div>
                </div>
            </div>
            <div class="laglag dark">
                <div class="wp">
                    <div class="num">4</div>
                    <div class="htxt">Prepaid</div>
                    <div class="stxt">致富项目预付款</div>
                </div>
            </div>
            <div class="laglag double">
                <div class="wp">
                    <div class="num">5</div>
                    <div class="htxt">Design</div>
                    <div class="stxt">启动项目[项目分析-创意研讨-方向确立-设计执行-提案制作]</div>
                </div>
            </div>
            <div class="laglag">
                <div class="wp">
                    <div class="num">6</div>
                    <div class="htxt">Show</div>
                    <div class="stxt">成果提案 及 修改确认</div>
                </div>
            </div>
            <div class="laglag dark">
                <div class="wp">
                    <div class="num">7</div>
                    <div class="htxt">Final Payment</div>
                    <div class="stxt">支付项目尾款</div>
                </div>
            </div>
            <div class="laglag last">
                <div class="wp">
                    <div class="num">8</div>
                    <div class="htxt">End</div>
                    <div class="stxt">提交设计源文件 项目完结</div>
                </div>
            </div>
            <div class="clear"></div>
        </div>
    </div>

</div>

<div style="background:#0011E3;color:#FFF;">
    <div style="padding:100px 0 30px 0;text-align:center;font-size:38px;">
        <div style="margin-bottom:20px;">OUR TEAM</div>
        <img style="width:60px;height:60px;margin-bottom:90px;" src="/img/about/t19.jpg" />

        <style>
            .mnaietab {
                width: 1100px;margin:auto;
            }
            .mnaietab tr td {
                text-align:center;
                width:14%;
                font-size: 14px;
            }
            .mnaietab tr td:first-child, .mnaietab tr td:last-child {
                width:15%;
            }
            .imgeir, .imgeirhover {
                background:url(/img/about/photo/r1.jpg) center center no-repeat;
                background-size: cover;
                width:100px;
                height:100px;
                display:inline-block;
                margin-bottom:10px;
                border-radius:200px;
            }
            .imgeirhover {
                display:none;
            }
            .mnaietab tr td:hover .imgeir {
                display:none;
            }
            .mnaietab tr td:hover .imgeirhover {
                display:inline-block;
            }
            .jobtdir {
                font-size:12px;
                font-style: italic;
                margin-bottom:90px;
            }
        </style>
        <table class="mnaietab">
            <tr>
                <td>
                    <div class="imgeir"></div>
                    <div class="imgeirhover" style="background-image:url(/img/about/photo/r1-c.jpg);"></div>
                    <div class="namedir">ERIC</div>
                    <div class="jobtdir">Creative Director</div>
                </td>
                <td>
                    <div class="imgeir" style="background-image:url(/img/about/photo/r2.jpg);"></div>
                    <div class="imgeirhover" style="background-image:url(img/about/photo/r2-c.jpg);"></div>
                    <div class="namedir">XIE</div>
                    <div class="jobtdir">Creative Director</div>
                </td>
                <td>
                    <div class="imgeir" style="background-image:url(/img/about/photo/r3.jpg);"></div>
                    <div class="imgeirhover" style="background-image:url(/img/about/photo/r3-c.jpg);"></div>
                    <div class="namedir">EDDY</div>
                    <div class="jobtdir">Account Executive</div>
                </td>
                <td>
                    <div class="imgeir" style="background-image:url(/img/about/photo/r4.jpg);"></div>
                    <div class="imgeirhover" style="background-image:url(/img/about/photo/r4-c.jpg);"></div>
                    <div class="namedir">LAM</div>
                    <div class="jobtdir">Account Executive</div>
                </td>
                <td>
                    <div class="imgeir" style="background-image:url(/img/about/photo/r5.jpg);"></div>
                    <div class="imgeirhover" style="background-image:url(/img/about/photo/r5-c.jpg);"></div>
                    <div class="namedir">HONG</div>
                    <div class="jobtdir">Account Manage</div>
                </td>
                <td>
                    <div class="imgeir" style="background-image:url(/img/about/photo/r6.jpg);"></div>
                    <div class="imgeirhover" style="background-image:url(/img/about/photo/r6-c.jpg);"></div>
                    <div class="namedir">TENG</div>
                    <div class="jobtdir">Art Director</div>
                </td>
                <td>
                    <div class="imgeir" style="background-image:url(/img/about/photo/r7.jpg);"></div>
                    <div class="imgeirhover" style="background-image:url(/img/about/photo/r7-c.jpg);"></div>
                    <div class="namedir">STEP</div>
                    <div class="jobtdir">Media Planner</div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="imgeir" style="background-image:url(/img/about/photo/r8.jpg);"></div>
                    <div class="imgeirhover" style="background-image:url(/img/about/photo/r8-c.jpg);"></div>
                    <div class="namedir">LINO</div>
                    <div class="jobtdir">Account Manage</div>
                </td>
                <td>
                    <div class="imgeir" style="background-image:url(/img/about/photo/r9.jpg);"></div>
                    <div class="imgeirhover" style="background-image:url(/img/about/photo/r9-c.jpg);"></div>
                    <div class="namedir">SAM</div>
                    <div class="jobtdir">Account Director</div>
                </td>
                <td>
                    <div class="imgeir" style="background-image:url(/img/about/photo/r10.jpg);"></div>
                    <div class="imgeirhover" style="background-image:url(/img/about/photo/r10-c.jpg);"></div>
                    <div class="namedir">MING</div>
                    <div class="jobtdir">Senior Art Director</div>
                </td>
                <td>
                    <div class="imgeir" style="background-image:url(/img/about/photo/r11.jpg);"></div>
                    <div class="imgeirhover" style="background-image:url(/img/about/photo/r11-c.jpg);"></div>
                    <div class="namedir">YUCHENG</div>
                    <div class="jobtdir">TV Producer</div>
                </td>
                <td>
                    <div class="imgeir" style="background-image:url(/img/about/photo/r12.jpg);"></div>
                    <div class="imgeirhover" style="background-image:url(/img/about/photo/r12-c.jpg);"></div>
                    <div class="namedir">JASH</div>
                    <div class="jobtdir">Production Manage</div>
                </td>
                <td>
                    <div class="imgeir" style="background-image:url(/img/about/photo/r13.jpg);"></div>
                    <div class="imgeirhover" style="background-image:url(/img/about/photo/r13-c.jpg);"></div>
                    <div class="namedir">DAMING</div>
                    <div class="jobtdir">Finish Artist</div>
                </td>
                <td>
                    <div class="imgeir" style="background-image:url(/img/about/photo/r14.jpg);"></div>
                    <div class="imgeirhover" style="background-image:url(/img/about/photo/r14-c.jpg);"></div>
                    <div class="namedir">KE</div>
                    <div class="jobtdir">Copy Director</div>
                </td>
            </tr>
        </table>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $('#tab_3').addClass('selected');
    })
</script>