<!--<div style="background:#0011E3;color:#FFF;font-size:18px;height:80px;line-height:80px;text-align:center;">-->
<!--    ABOUT US-->
<!--</div>-->
<!--<div style="background:#171b60">-->
<!--    <div class="container">-->
<!--        <div class="row">-->
<!--            <div class="col-xs-12">-->
<!--                <div style="padding-top:30px;">-->
<!--                    <img src="/img/vrabout.jpg" width="100%" style="box-shadow: 0 0 20px rgba(0,0,0,.3)"/>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->
<style>
    .dwimg {
        width:100%;
    }
</style>
<div style="height:80px"></div>
<img src="/img/about/slides/1.jpg" class="dwimg"/>
<img src="/img/about/slides/2.jpg" class="dwimg"/>
<img src="/img/about/slides/3.jpg" class="dwimg"/>
<img src="/img/about/slides/4.jpg" class="dwimg"/>
<img src="/img/about/slides/5.jpg" class="dwimg"/>
<img src="/img/about/slides/6.jpg" class="dwimg"/>
<img src="/img/about/slides/7.jpg" class="dwimg"/>
<img src="/img/about/slides/8.jpg" class="dwimg"/>
<img src="/img/about/slides/9.jpg" class="dwimg"/>
<img src="/img/about/slides/10.jpg" class="dwimg"/>
<img src="/img/about/slides/11.jpg" class="dwimg"/>
<img src="/img/about/slides/12.jpg" class="dwimg"/>
<img src="/img/about/slides/13.jpg" class="dwimg"/>
<img src="/img/about/slides/14.jpg" class="dwimg"/>
<img src="/img/about/slides/15.jpg" class="dwimg"/>
<img src="/img/about/slides/16.jpg" class="dwimg"/>
<img src="/img/about/slides/17.jpg" class="dwimg"/>
<img src="/img/about/slides/18.jpg" class="dwimg"/>
<img src="/img/about/slides/19.jpg" class="dwimg"/>

<!--<div style="background:#0011E3;color:#FFF;">-->
<!--    <div style="padding:100px 0 30px 0;text-align:center;font-size:38px;">-->
<!--        <div style="margin-bottom:20px;">OUR TEAM</div>-->
<!--        <img style="width:60px;height:60px;margin-bottom:90px;" src="/img/about/t19.jpg" />-->
<!---->
<!--        <style>-->
<!--            .mnaietab {-->
<!--                width: 1100px;margin:auto;-->
<!--            }-->
<!--            .mnaietab tr td {-->
<!--                text-align:center;-->
<!--                width:14%;-->
<!--                font-size: 14px;-->
<!--            }-->
<!--            .mnaietab tr td:first-child, .mnaietab tr td:last-child {-->
<!--                width:15%;-->
<!--            }-->
<!--            .imgeir, .imgeirhover {-->
<!--                background:url(/img/about/photo/r1.jpg) center center no-repeat;-->
<!--                background-size: cover;-->
<!--                width:100px;-->
<!--                height:100px;-->
<!--                display:inline-block;-->
<!--                margin-bottom:10px;-->
<!--                border-radius:200px;-->
<!--            }-->
<!--            .imgeirhover {-->
<!--                display:none;-->
<!--            }-->
<!--            .mnaietab tr td:hover .imgeir {-->
<!--                display:none;-->
<!--            }-->
<!--            .mnaietab tr td:hover .imgeirhover {-->
<!--                display:inline-block;-->
<!--            }-->
<!--            .jobtdir {-->
<!--                font-size:12px;-->
<!--                font-style: italic;-->
<!--                margin-bottom:90px;-->
<!--            }-->
<!--        </style>-->
<!--        <table class="mnaietab">-->
<!--            <tr>-->
<!--                <td>-->
<!--                    <div class="imgeir"></div>-->
<!--                    <div class="imgeirhover" style="background-image:url(/img/about/photo/r1-c.jpg);"></div>-->
<!--                    <div class="namedir">ERIC</div>-->
<!--                    <div class="jobtdir">Creative Director</div>-->
<!--                </td>-->
<!--                <td>-->
<!--                    <div class="imgeir" style="background-image:url(/img/about/photo/r2.jpg);"></div>-->
<!--                    <div class="imgeirhover" style="background-image:url(/img/about/photo/r2-c.jpg);"></div>-->
<!--                    <div class="namedir">XIE</div>-->
<!--                    <div class="jobtdir">Creative Director</div>-->
<!--                </td>-->
<!--                <td>-->
<!--                    <div class="imgeir" style="background-image:url(/img/about/photo/r3.jpg);"></div>-->
<!--                    <div class="imgeirhover" style="background-image:url(/img/about/photo/r3-c.jpg);"></div>-->
<!--                    <div class="namedir">EDDY</div>-->
<!--                    <div class="jobtdir">Account Executive</div>-->
<!--                </td>-->
<!--                <td>-->
<!--                    <div class="imgeir" style="background-image:url(/img/about/photo/r4.jpg);"></div>-->
<!--                    <div class="imgeirhover" style="background-image:url(/img/about/photo/r4-c.jpg);"></div>-->
<!--                    <div class="namedir">LAM</div>-->
<!--                    <div class="jobtdir">Account Executive</div>-->
<!--                </td>-->
<!--                <td>-->
<!--                    <div class="imgeir" style="background-image:url(/img/about/photo/r5.jpg);"></div>-->
<!--                    <div class="imgeirhover" style="background-image:url(/img/about/photo/r5-c.jpg);"></div>-->
<!--                    <div class="namedir">HONG</div>-->
<!--                    <div class="jobtdir">Account Manage</div>-->
<!--                </td>-->
<!--                <td>-->
<!--                    <div class="imgeir" style="background-image:url(/img/about/photo/r6.jpg);"></div>-->
<!--                    <div class="imgeirhover" style="background-image:url(/img/about/photo/r6-c.jpg);"></div>-->
<!--                    <div class="namedir">TENG</div>-->
<!--                    <div class="jobtdir">Art Director</div>-->
<!--                </td>-->
<!--                <td>-->
<!--                    <div class="imgeir" style="background-image:url(/img/about/photo/r7.jpg);"></div>-->
<!--                    <div class="imgeirhover" style="background-image:url(/img/about/photo/r7-c.jpg);"></div>-->
<!--                    <div class="namedir">STEP</div>-->
<!--                    <div class="jobtdir">Media Planner</div>-->
<!--                </td>-->
<!--            </tr>-->
<!--            <tr>-->
<!--                <td>-->
<!--                    <div class="imgeir" style="background-image:url(/img/about/photo/r8.jpg);"></div>-->
<!--                    <div class="imgeirhover" style="background-image:url(/img/about/photo/r8-c.jpg);"></div>-->
<!--                    <div class="namedir">LINO</div>-->
<!--                    <div class="jobtdir">Account Manage</div>-->
<!--                </td>-->
<!--                <td>-->
<!--                    <div class="imgeir" style="background-image:url(/img/about/photo/r9.jpg);"></div>-->
<!--                    <div class="imgeirhover" style="background-image:url(/img/about/photo/r9-c.jpg);"></div>-->
<!--                    <div class="namedir">SAM</div>-->
<!--                    <div class="jobtdir">Account Director</div>-->
<!--                </td>-->
<!--                <td>-->
<!--                    <div class="imgeir" style="background-image:url(/img/about/photo/r10.jpg);"></div>-->
<!--                    <div class="imgeirhover" style="background-image:url(/img/about/photo/r10-c.jpg);"></div>-->
<!--                    <div class="namedir">MING</div>-->
<!--                    <div class="jobtdir">Senior Art Director</div>-->
<!--                </td>-->
<!--                <td>-->
<!--                    <div class="imgeir" style="background-image:url(/img/about/photo/r11.jpg);"></div>-->
<!--                    <div class="imgeirhover" style="background-image:url(/img/about/photo/r11-c.jpg);"></div>-->
<!--                    <div class="namedir">YUCHENG</div>-->
<!--                    <div class="jobtdir">TV Producer</div>-->
<!--                </td>-->
<!--                <td>-->
<!--                    <div class="imgeir" style="background-image:url(/img/about/photo/r12.jpg);"></div>-->
<!--                    <div class="imgeirhover" style="background-image:url(/img/about/photo/r12-c.jpg);"></div>-->
<!--                    <div class="namedir">JASH</div>-->
<!--                    <div class="jobtdir">Production Manage</div>-->
<!--                </td>-->
<!--                <td>-->
<!--                    <div class="imgeir" style="background-image:url(/img/about/photo/r13.jpg);"></div>-->
<!--                    <div class="imgeirhover" style="background-image:url(/img/about/photo/r13-c.jpg);"></div>-->
<!--                    <div class="namedir">DAMING</div>-->
<!--                    <div class="jobtdir">Finish Artist</div>-->
<!--                </td>-->
<!--                <td>-->
<!--                    <div class="imgeir" style="background-image:url(/img/about/photo/r14.jpg);"></div>-->
<!--                    <div class="imgeirhover" style="background-image:url(/img/about/photo/r14-c.jpg);"></div>-->
<!--                    <div class="namedir">KE</div>-->
<!--                    <div class="jobtdir">Copy Director</div>-->
<!--                </td>-->
<!--            </tr>-->
<!--        </table>-->
<!--    </div>-->
<!--</div>-->
<script type="text/javascript">
    $(document).ready(function() {
        $('#tab_3').addClass('selected');
        $('.xtopbne.relative').removeClass('relative').addClass('fixed');
    })
</script>