<div class="container breadc">
    <div class="cn" style="display: none">
        <div class="row">
            <div class="col-xs-12">
                <a href="/">首页</a>
                <span class="xsplt">/</span>
                <span class="xsexp">产品应用</span>
            </div>
        </div>
    </div>
    <div class="en" style="display: none">
        <div class="row">
            <div class="col-xs-12">
                <a href="/?language=en">Home</a>
                <span class="xsplt">/</span>
                <span class="xsexp">Applications</span>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="cn" style="display: none">
        <div class="row">
            <div class="col-xs-12">
                <div class="app-tt">
                    产品适用于：电子（工业厂房）、医药（净化房）、化工（防火车间）等
                </div>
                <div class="app-sub-tt">
                    <p>玻镁彩钢夹芯板</p>
                    <div>
                        玻镁夹芯板，是一种高强度、轻质、刚性大、防火、保温、防水、平整度高且不变形、隔音、防潮产品。<br />
                        广泛适用于：净化室、洁净厂房、组合移动房屋、间隔墙、特别适用于医药、电子、生物研究、食品、饮料等净化间的室内墙体用板。
                    </div>
                </div>
                <div style="margin-top:10px;height:780px;">
                    <img src="/img/app01.jpg" style="width:400px;position:absolute;left:0;top:0;"/>
                    <img src="/img/app02.jpg" style="width:400px;position:absolute;left:0;top:247px;"/>
                    <img src="/img/app03.jpg" style="width:400px;position:absolute;left:0;top:487px;"/>
                    <img src="/img/app04.jpg" style="width:660px;position:absolute;right:0;top:0;" />
                    <div style="width:220px;height:144px;position:absolute;left:410px;top:581px;overflow:hidden">
                        <img src="/img/app05.jpg" />
                    </div>
                    <div style="width:220px;height:144px;position:absolute;left:640px;top:581px;overflow:hidden">
                        <img src="/img/app06.jpg" />
                    </div>
                    <div style="width:200px;height:144px;position:absolute;left:870px;top:581px;overflow:hidden">
                        <img src="/img/app07.jpg" />
                    </div>
                </div>


                <div class="app-sub-tt">
                    <p>岩棉彩钢夹芯板</p>
                    <div>
                        岩棉彩钢夹芯板具有降低噪音的高效性能，特别适合于隔音要求高的场所。同时，它易于安装，还具有出色的防火功能、承重力大及表面平整不易变形。<br />
                        适用领域：广泛适用于钢结构厂房、简易活动房的屋面、墙体、空气洁净室的吊顶与隔断。
                    </div>
                </div>
                <div class="app-sub-tt" style="margin-top:10px;">
                    <p>聚苯乙烯彩钢夹芯板</p>
                    <div>
                        聚苯乙烯彩钢夹芯板是一种新型的建材产品，其质轻（容量为10-25kg/m3）、只有传统混凝土材料重量的1/20-1/30，且价格低廉，施工速度快，外形靓丽，韧性高不易变形。<br />
                        性能：集防水、防潮、隔音、保温等功能于一体。<br />
                        适用领域：各种大型厂房的屋面、墙体及空气洁净室的吊顶与隔断。
                    </div>
                </div>
                <div style="margin-top:10px;height:530px;">

                    <div style="width:670px;height:480px;position:absolute;left:0;top:0;overflow:hidden">
                        <img src="/img/app08.jpg" />
                    </div>
                    <div style="width:390px;height:230px;position:absolute;right:0;top:0;overflow:hidden">
                        <img src="/img/app09.jpg" />
                    </div>
                    <div style="width:390px;height:240px;position:absolute;right:0;top:240px;overflow:hidden">
                        <img src="/img/app10.jpg" />
                    </div>
                </div>

                <div style="margin-top:10px;height:720px;">
                    <div style="width:730px;position:absolute;right:0;top:0;background:#F0F0F0;height:190px;">
                        <div class="app-sub-tt">
                            <p>屋面隔热板</p>
                            <div>
                                屋面隔热板即瓦楞彩钢夹芯板、其采用彩色涂层钢板、镀锌板等金属板材经辊压冷湾成各种波形的夹芯彩钢瓦，<br />
                                它适用于工业与民用建筑、仓库、特种建筑、大跨度钢结构房屋的屋面。<br />
                                具有质轻、强度高、色泽丰富、施工方便快捷、抗震、防火、防雨、寿命长、免维护等特点，现已广泛推广应用于钢结构厂房、活动房的屋面材料。
                            </div>
                        </div>
                    </div>
                    <div style="width:330px;height:330px;position:absolute;left:0;top:0;overflow:hidden">
                        <img src="img/app11.jpg" />
                    </div>
                    <div style="width:730px;height:520px;position:absolute;right:0;top:200px;overflow:hidden">
                        <img src="img/app12.jpg" />
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="en" style="display: none">
        <div class="row">
            <div class="col-xs-12">
                <div class="app-tt">
                    Applications: Hand-made Sandwich Panel is widely used in Electronic industry (factory building), Medicine industry (Purifying Rooms), Chemical industry (Fire-resistant workshop) etc.
                </div>
                <div class="app-sub-tt">
                    <p>Glass Magnesium Sandwich Panel</p>
                    <div>
                        Glass Magnesium Sandwich Panel is a new product with features of high intensity, light weight, larger rigidity, fire resistance, high performance of heat and sound insulation, waterproof, well bearing-capacity, stable shape and moisture proof.<br />
                        It is widely used in purifying rooms, cleaning workshops, combined movable houses, partition walls, like medicine, electronics, food beverage and biology research industries.
                    </div>
                </div>
                <div style="margin-top:10px;height:780px;">
                    <img src="img/app01.jpg" style="width:400px;position:absolute;left:0;top:0;"/>
                    <img src="img/app02.jpg" style="width:400px;position:absolute;left:0;top:247px;"/>
                    <img src="img/app03.jpg" style="width:400px;position:absolute;left:0;top:487px;"/>
                    <img src="img/app04.jpg" style="width:660px;position:absolute;right:0;top:0;" />
                    <div style="width:220px;height:144px;position:absolute;left:410px;top:581px;overflow:hidden">
                        <img src="img/app05.jpg" />
                    </div>
                    <div style="width:220px;height:144px;position:absolute;left:640px;top:581px;overflow:hidden">
                        <img src="img/app06.jpg" />
                    </div>
                    <div style="width:200px;height:144px;position:absolute;left:870px;top:581px;overflow:hidden">
                        <img src="img/app07.jpg" />
                    </div>
                </div>
                <div class="app-sub-tt">
                    <p>Rock wool Sandwich Panel</p>
                    <div>
                        Rock wool Sandwich Panel has a fine feature in noise reduction, especially suitable for the place which need high performance of sound-insulation. Also, it has excellent fire-resistance, easy installation, well bearing-capacity and stable shape advantages<br />
                        Application: steel structure workshop, roof and walls of prefab house, ceiling and partition wall of air purifying rooms.
                    </div>
                </div>
                <div class="app-sub-tt" style="margin-top:10px;">
                    <p>(Polystyrene) EPS Sandwich Panel</p>
                    <div>
                        (Polystyrene) EPS Sandwich Panel is a new kind of building board with quite light-weight (10-25kg/m3), just 1/20 - 1/30 weight of the concrete meterials. It has advantages of good price, simple and quick installation, beautiful shape and high toughness.<br />
                        Features: waterproof, moisture proof, sound proof and heat insulated.<br />
                        Application: suitable for the roofs and walls for various kinds of large-scale factories, and the ceiling and partition of air purification room.
                    </div>
                </div>
                <div style="margin-top:10px;height:530px;">

                    <div style="width:670px;height:480px;position:absolute;left:0;top:0;overflow:hidden">
                        <img src="img/app08.jpg" />
                    </div>
                    <div style="width:390px;height:230px;position:absolute;right:0;top:0;overflow:hidden">
                        <img src="img/app09.jpg" />
                    </div>
                    <div style="width:390px;height:240px;position:absolute;right:0;top:240px;overflow:hidden">
                        <img src="img/app10.jpg" />
                    </div>
                </div>
                <div style="margin-top:10px;height:720px;">
                    <div style="width:730px;position:absolute;right:0;top:0;background:#F0F0F0;height:240px;">
                        <div class="app-sub-tt">
                            <p>Insulated Roofing Sandwich Panel</p>
                            <div>
                                Insulated Roofing Sandwich Panel, called Corrugated Panel is made of color coated steel sheet, galvanized sheet metal plate, and been rolly bended into wave-type sandwich panel, it is suitable for industrial and civil buildings, warehouses, special construction and large-span steel structure roof.<br />
                                Because of the characteristics of light weight, larger rigidity, easy installation, seismic resistance, fire resistance, waterproof, long service life and maintenance free, this meterial has now been widely applied to the roofing materials of steel structural factories, prefab houses.
                            </div>
                        </div>
                    </div>
                    <div style="width:330px;height:330px;position:absolute;left:0;top:0;overflow:hidden">
                        <img src="img/app11.jpg" />
                    </div>
                    <div style="width:730px;height:520px;position:absolute;right:0;top:250px;overflow:hidden">
                        <img src="img/app12.jpg" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="clear-50"></div>
<script type="text/javascript">
    $(document).ready(function() {
        $(".header").find(".selected").removeClass("selected");
        $(".header").find(".application").addClass("selected");
    });
</script>