<div class="sub0-ejii">
    <div class="container breadc">
        <div class="cn" style="display: none">
            <div class="row">
                <div class="col-xs-12">
                    <a href="/">首页</a>
                    <span class="xsplt">/</span>
                    <span class="xsexp">荣誉资质</span>
                </div>
            </div>
        </div>
        <div class="en" style="display: none">
            <div class="row">
                <div class="col-xs-12">
                    <a href="/?language=en">Home</a>
                    <span class="xsplt">/</span>
                    <span class="xsexp"> Qualification & Certification</span>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="cn" style="display: none">
            <div class="row">
                <div class="col-xs-12">
                    <div class="ttinbg">资质证书</div>
                    <div class="ttinbg2">
                        经过普源人不懈地努力，以专业优质的服务，得到了社会各界的认可，收获了今天的累累硕果。
                    </div>
                </div>
            </div>
        </div>
        <div class="en" style="display: none">
            <div class="row">
                <div class="col-xs-12">
                    <div class="ttinbg">Certification</div>
                    <div class="ttinbg2">
                        Out Certification Wall
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="clear-30"></div>
    <div class="container">
        <div class="row">
            <div class="col-xs-12 vxxr4e">
                <img src="img/awards-1.jpg" />
                <img src="img/awards-2.jpg" />
                <img src="img/awards-3.jpg" />
                <img src="img/awards-4.jpg" />
                <img class="end" src="img/awards-5.jpg" />
                <img src="img/awards-6.jpg" />
                <img src="img/awards-7.jpg" />
                <img src="img/awards-8.jpg" />
                <img src="img/awards-9.jpg" />
                <img class="end" src="img/awards-10.jpg" />
                <img src="img/awards-11.jpg" />
                <img src="img/awards-12.jpg" />
                <img src="img/awards-13.jpg" />
                <img src="img/awards-14.jpg" />
                <img class="end" src="img/awards-15.jpg" />
            </div>
        </div>
    </div>
    <div class="clear"></div>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $(".header").find(".selected").removeClass("selected");
        $(".header").find(".certification").addClass("selected");
    });
</script>