<div class="detailcortn">
    <div class="container">
        <div class="col-xs-2">
            &nbsp;
        </div>
        <div class="col-xs-8">
            <div class="detailmte"><?php echo $this->model->name ?></div>
            <div class="detailmte2"><?php echo $this->model->label ?></div>
            <div class="tscrow">Team: <?php echo $this->model->team ?></div>
            <div class="tscrow">Art Director: <?php echo $this->model->art_director ?></div>
            <div class="tscrow">Creative Director: <?php echo $this->model->creative_director ?></div>
            <div class="tscrow">Time Of Design : <?php echo $this->model->time_of_design ?></div>
            <div class="tscrow">Type : <?php echo $this->model->type ?></div>
            <!--            <div class="tscrow">行業屬性：--><?php //echo $this->model->property ?><!--</div>-->
            <div class="tscrow">行業屬性：
                <?php $index = 0; ?>
                <?php foreach ($this->model->category as $c) : ?>
                    <?php
                    if ($index > 0) {
                        echo '/';
                    }
                    ?>
                    <a class="catieim" href="<?php echo "/home/list/" . $c->id ?>"><?php echo $c->name;
                        $index++ ?></a>
                <?php endforeach; ?>
            </div>
            <div class="detailmte3"></div>
            <div class="detailmte4"><?php echo $this->model->description ?></div>
        </div>
        <div class="col-xs-2">
            &nbsp;
        </div>
    </div>
</div>
<style>
    .detailgalleryitm {
        background: url(/img/photos/case/vapeangle/small01.jpg) center center no-repeat;
        background-size: cover;
        width: 108px;
        height: 70px;
        float: left;
        display: inline-block;
        margin-right: 7px;
        cursor: pointer;
    }

    .detailgalleryitm .clr {
        width: 100%;
        height: 100%;
        position: absolute;
        left: 0;
        top: 0;
        background: rgba(255, 255, 255, .7);
        display: block;
    }

    .detailgalleryitm.selected .clr, .detailgalleryitm:hover .clr {
        display: none;
    }

    .detailgalleryitm.selected {
        box-shadow: inset 0 0 0 2px #0110e3;
    }

    .detailgallerylr {
        border:none;
        display: inline-block;
        height: 70px;
        width: 60px;
        position: absolute;
        left: -60px;
        top: 50%;
        margin-top: -35px;
        color: #aaa;
        text-align: center;
        line-height: 66px;
        font-size: 32px;
        cursor: pointer;
        padding:0;
    }

    .detailgallerylr:hover {
        background-color: rgba(0, 0, 0, .03);
        color: #0011E7;
    }

    .detailgallerylr.rt {
        left: auto;
        right: -60px;
    }

    .bist01 {
        background: #FFF;
    }

    .bist02 {
        padding-top: 50px;
        padding-bottom: 20px;
    }

    .bist03 {
        width: 100%;
        height: 400px;
        background: #333;
        position: relative;
    }
    .bist03.sm {
        height: 160px;
    }
    .bist04 {
        width: 100%;
        height: 100%;
        position: absolute;
        left: 0;
        top: 0;
        background: url(/img/bg03.jpg) center center no-repeat;
        background-size: cover;
    }

    .bist05 {
        margin-top: 30px;
        overflow: hidden;
        height: 70px;
    }

    .bist06 {
        width: 10980px;
        position: absolute;
        left: 0;
        top: 0;
        height: 100%;
    }

    .bist07 {
        padding-bottom: 50px;
        color: #ccc;
    }

    .bist08 {
        padding-bottom: 80px;
    }
</style>

<div class="bist01">
    <div class="container bist02">

        <div class="col-xs-2">&nbsp;</div>
        <div class="col-xs-8">
            <div class="bist03">
                <?php
                $firstbigimg = "";
                if($this->model->show_gif) {
                    $firstbigimg = "/photo/image/" . $this->model->show_gif;
                } else if (count($this->model->photo)) {
                    $ap = $this->model->photo[0];
                    $firstbigimg = $this->photoImage($ap->name . $ap->type, 'orig');
                }
                $firstbigimg = "style='background-image:url(" . $firstbigimg . ");'";
                ?>
                <div class="bist04" id="bigshowfrm" <?php echo $firstbigimg ?>></div>
            </div>
            <div>
                <a href="javascript:void(0)" class="detailgallerylr lt iconfont icon-angleleft"></a>
                <a href="javascript:void(0)" class="detailgallerylr rt iconfont icon-angleright"></a>

                <div class="bist05">
                    <div class="bist06 di4irt">

                        <?php $i = 0 ?>
                        <?php if($this->model->gif): ?>
                            <div index="<?php echo $i + 1 ?>"
                                 source="/photo/image/<?php echo $this->model->show_gif ?>"
                                 class="detailgalleryitm selected"
                                 style="background-image: url(/photo/image/<?php echo $this->model->gif ?>);">
                                <div class="clr"></div>
                            </div>
                            <?php $i = 1; ?>
                        <?php endif;?>


                        <?php foreach ($this->model->photo as $p) : ?>
                            <?php
                            $clse = "";
                            if ($i == 0) {
                                $clse = "selected";
                            }
                            ?>

                            <div index="<?php echo $i + 1 ?>"
                                 source="<?php echo $this->photoImage($p->name . $p->type, 'large') ?>"
                                 class="detailgalleryitm <?php echo $clse ?>"
                                 style="background-image: url(<?php echo $this->photoImage($p->name . $p->type, 'main') ?>);">
                                <div class="clr"></div>
                            </div>
                            <?php $i++; ?>
                        <?php endforeach; ?>

                    </div>
                </div>
            </div>

        </div>
        <div class="col-xs-2">&nbsp;</div>

    </div>
    <div class="container bist07">
        <div class="col-xs-2">&nbsp;</div>
        <div class="col-xs-10">
            <span>Images <span id="bttip_index">1</span> / <span
                    id="bttip_tt"><?php echo count($this->model->photo) ?></span></span>
        </div>
    </div>
</div>


<div class="home_block bist08">
    <div class="container">
        <div class="row">
            <?php $c = 0; ?>
            <?php foreach ($this->products as $p) : ?>
            <?php if ($p->id == $this->model->id) : ?>
            <div class="col-xs-4 ceitem selected" id="<?php echo $p->id ?>">
                <?php else : ?>
                <div class="col-xs-4 ceitem" id="<?php echo $p->id ?>">
                    <?php endif; ?>
                    <a target="_blank" href="/home/case/<?php echo $p->id ?>" class="ceitemct">
                        <?php
                        $thumbnailimg = $this->photoImage($p->photo[0]->name . $p->photo[0]->type, 'main');
                        if($p->gif) {
                            $thumbnailimg = '/photo/image/' . $p->gif;
                        }
                        ?>
                        <span style="background-image:url(<?php echo $thumbnailimg ?>);" class="img"></span>
                    </a>
                    <a target="_blank" href="/home/case/<?php echo $p->id ?>" class="txt"><?php echo $p->name ?></a>

                    <div class="txt2">
                        <?php foreach ($p->category as $c) : ?>
                            <a href="/home/list/<?php echo $c->id ?>"><?php echo $c->name ?></a>
                        <?php endforeach; ?>
                    </div>
                </div>
                <?php $c++; ?>
                <?php
                if ($c == 4) {
                    $c = 0;
                }
                ?>
                <?php endforeach; ?>

            </div>
        </div>
    </div>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#tab_2').addClass('selected');

            $('.detailgalleryitm').click(function () {
                var imgurl = $(this).attr('source');
                $('#bigshowfrm').css('background-image', 'url("' + imgurl + '")');
                $('.detailgalleryitm').removeClass('selected');
                $(this).addClass('selected');
                var index = $(this).attr('index');
                $('#bttip_index').text(index);

                slideBtSie();
            });

            $('.detailgallerylr.lt').click(function () {
                var i = $('.detailgalleryitm.selected').attr('index');
                i--;
                if (i === 0) {
                    i = 1;
                }
                $('.detailgalleryitm[index=' + i + ']').click();
            });
            $('.detailgallerylr.rt').click(function () {
                var i = $('.detailgalleryitm.selected').attr('index');
                i++;
                var max = parseInt($('#bttip_tt').val());
                if (i > max) {
                    i = max;
                }
                $('.detailgalleryitm[index=' + i + ']').click();
            });
        });
        function slideBtSie() {
            var selected = $('.detailgalleryitm.selected');
            var index = selected.attr('index');
            var pg = Math.ceil(index / 5) - 1;
            var offset = pg * -1 * 5 * (108 + 7);
            $('.di4irt').animate({
                left: offset + "px"
            }, 400);
        }


    </script>