<div class="container breadc">
    <div class="row">
        <div class="col-xs-12">
            <a href="#">首页</a>
            <span class="xsplt">/</span>
            <span class="xsexp">净化板材系列</span>
        </div>
    </div>
</div>

<div class="container mb30">
    <div class="row">
        <div class="col-xs-3">
            <ul class="sid-ul-lst">
                <li class="selected">
                    <a href="#">
                        全部
                    </a>
                </li>
<!--                <li>-->
<!--                    <a href="#">-->
<!--                        混凝土材料板材-->
<!--                    </a>-->
<!--                </li>-->
<!--                <li>-->
<!--                    <a href="#">-->
<!--                        预制板材料板材-->
<!--                    </a>-->
<!--                </li>-->
<!--                <li>-->
<!--                    <a href="#">-->
<!--                        实木材料板材-->
<!--                    </a>-->
<!--                </li>-->
            </ul>
        </div>
        <div class="col-xs-9">
            <div>
<!--                <div class="gallsitm">-->
<!--                    <a href="product.htm" class="imga" style="background-image:url(img/l-08.jpg)"></a>-->
<!--                    <a href="product.htm" class="nmtt">产品名称1</a>-->
<!--                </div>-->
<!--                <div class="gallsitm">-->
<!--                    <a href="product.htm" class="imga" style="background-image:url(img/l-08.jpg)"></a>-->
<!--                    <a href="product.htm" class="nmtt">产品名称1</a>-->
<!--                </div>-->
<!--                <!-- 每隔3个为1行，每一行末尾的gallsitm加上一个class:last -->-->
<!--                <div class="gallsitm last">-->
<!--                    <a href="product.htm" class="imga" style="background-image:url(img/l-08.jpg)"></a>-->
<!--                    <a href="product.htm" class="nmtt">产品名称1</a>-->
<!--                </div>-->
<!--                <!--每一行末尾加上一个clear来保持高度-->-->
<!--                <div class="clear"></div>-->
<!--                <div class="gallsitm">-->
<!--                    <a href="product.htm" class="imga" style="background-image:url(img/l-08.jpg)"></a>-->
<!--                    <a href="product.htm" class="nmtt">产品名称1</a>-->
<!--                </div>-->
<!--                <div class="gallsitm">-->
<!--                    <a href="product.htm" class="imga" style="background-image:url(img/l-08.jpg)"></a>-->
<!--                    <a href="product.htm" class="nmtt">产品名称1</a>-->
<!--                </div>-->
<!--                <div class="gallsitm last">-->
<!--                    <a href="product.htm" class="imga" style="background-image:url(img/l-08.jpg)"></a>-->
<!--                    <a href="product.htm" class="nmtt">产品名称1</a>-->
<!--                </div>-->
<!--                <div class="clear"></div>-->
<!--                <div class="gallsitm">-->
<!--                    <a href="product.htm" class="imga" style="background-image:url(img/l-08.jpg)"></a>-->
<!--                    <a href="product.htm" class="nmtt">产品名称1</a>-->
<!--                </div>-->
            </div>
            <div class="clear"></div>
        </div>
    </div>
</div>