<div class="home_block" style="background-image:url(/img/bg02.jpg);padding-top:180px;padding-bottom:180px;">
    <div style="text-align: center;color:#FFF;line-height:32px;width:550px;margin:0 auto;">
        <div style="font-weight:bold;font-size:24px;margin-bottom:40px;">CONTACT US</div>
        <span style="font-size:20px;" class="iconfont icon-mail"></span>
        <div><?php echo $this->model->email1 ?></div>
        <div style="margin-bottom:40px;"><?php echo $this->model->email2 ?></div>
        <span style="font-size:20px;" class="iconfont icon-home"></span>
        <div><?php echo $this->model->company_address ?></div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $('#tab_4').addClass('selected');
    })
</script>