<div id="tv-frame">
    <div class="board">
        <div class="title">
            <?php echo $this->title ?>
        </div>
        <div class="content">
            <form method="post" id="validate-form">
                <div class="bdrow">
                    <span class="font12px">请输入您的邮箱地址，我们将会通过邮件帮您找回密码</span>
                </div>
                <div class="bdrow">
                    <input type="text" placeholder="用户邮箱" id="email" name="email" value="<?php echo $this->re_email ?>" data-toggle="popover" data-trigger ="manual" data-placement="right"/>
                </div>
                <div class="bdrow">
                    <button type="submit" id="confirm-btn">发送邮件</button>
                </div>
            </form>
        </div>
        <div class="bottom">
            <a href="<?php echo $this->url(array(), 'login') ?>">重新登录？</a>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
<?php if ($this->send): ?>
            $('.content').paper({type: 'success', additionalClass: 'sign-gotmsg'}, '<b class="glyphicon glyphicon-ok-sign"></b> 密码发送成功，请登录您的邮箱获取最新密码</a>');
<?php endif; ?>
<?php if ($this->error): ?>
            $('.content').paper({type: 'danger', additionalClass: 'sign-gotmsg'}, '<b class="glyphicon glyphicon-minus-sign"></b> <?php echo $this->error ?>');
<?php endif; ?>
        $("#validate-form").validate({
            rules: {
                "email": {
                    required: true,
                    email: true
                }
            }
        });

//        $('#confirm-btn').click(function() {
//
//            $('.content').valid();
//
//            return;
//            var email = $('#email').val();
//            $.ajax({
//                url: '<?php echo $this->url(array(), 'forgot-password') ?>',
//                dataType: 'json',
//                type: 'post',
//                data: {email: email},
//                success: function(response) {
//                    if (response === 1) {
//
//                    } else {
//
//                    }
//                }
//            });
//        });
    });
</script>