<div class="home_block fullheight" style="background-image:url(img/bg01.jpg);">
    <div class="bigvr1"></div>
</div>

<div class="home_block" style="padding:80px 0;">
    <div class="container bgwtitle">
        <div class="col-xs-4">&nbsp;</div>
        <div class="col-xs-4">
<!--            <div>-->
<!--                <div class="t1">设&nbsp;&nbsp;计&nbsp;&nbsp;案&nbsp;&nbsp;例</div>-->
<!--                <div class="t2">C A S E&nbsp;&nbsp;&nbsp;&nbsp;S H O W</div>-->
<!--            </div>-->

            <div>
                <div class="t1" style="margin-bottom:50px;">CASE</div>
            </div>
        </div>
        <div class="col-xs-4"></div>
    </div>
    <div class="container">
        <div class="row">
        <?php $c = 0; ?>
        <?php foreach ($this->product as $p) :?>

            <div class="col-xs-4 ceitem" id="<?php echo $p->id ?>">
                <a target="_blank" href="/home/case/<?php echo $p->id ?>" class="ceitemct">
                    <?php
                    $thumbnailimg = $this->photoImage($p->photo[0]->name . $p->photo[0]->type, 'main');
                    if($p->gif) {
                        $thumbnailimg = '/photo/image/' . $p->gif;
                    }
                    ?>
                    <span style="background-image:url(<?php echo $thumbnailimg ?>);" class="img"></span>
                </a>
                <a target="_blank" href="/home/case/<?php echo $p->id ?>" class="txt"><?php echo $p->name ?></a>
                <div class="txt2">
                    <?php foreach ($p->category as $c) :?>
                        <a href="/home/list/<?php echo $c->id ?>"><?php echo $c->name ?></a>
                    <?php endforeach; ?>
                </div>
            </div>

            <?php $c ++; ?>
            <?php
                if ($c == 3) {
                    $c = 0;
                }
            ?>
        <?php endforeach; ?>
        </div>
    </div>



</div>