<div style="background:#FFF;padding:50px 0;">
    <div class="container bgwtitle">
        <div class="col-xs-4">&nbsp;</div>
        <div class="col-xs-4">
<!--            <div>-->
<!--                <div class="t1">分&nbsp;&nbsp;类&nbsp;&nbsp;展&nbsp;&nbsp;示</div>-->
<!--                <div class="t2">C A T E G O R Y</div>-->
<!--            </div>-->


            <div>
                <div class="t1" style="margin-bottom:50px;">CASE</div>
            </div>
        </div>
        <div class="col-xs-4"></div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-xs-2">
                <ul class="categorysideul">
                    <?php
                    $acls = "";
                    if(!$this->cid) {
                        $acls="selected";
                    }
                    ?>
                    <li class="<?php echo $acls ?>" id="all"><a href="/home/list">所有分类<i class="iconfont icon-angleright"></i></a></li>
                    <?php foreach ($this->categorys as $c) :?>
                        <?php
                        $cls = "";
                        if($c->id == $this->cid) {
                            $cls="selected";
                        }
                        ?>
                        <li class="<?php echo $cls ?>" id="<?php echo $c->id ?>"><a href="/home/list/<?php echo $c->id ?>"><?php echo $c->name ?><i class="iconfont icon-angleright"></i></a></li>
                    <?php endforeach; ?>
                </ul>
            </div>
            <div class="col-xs-10">
                <?php foreach ($this->paginator as $p) :?>
                    <div class="col-xs-4 ceitem" id="<?php echo $p->id ?>">
                        <a href="/home/case/<?php echo $p->id ?>" class="ceitemct">
                            <img src="<?php echo $this->photoImage($p->photo[0]->name . $p->photo[0]->type, 'main') ?>" class="img" />
                        </a>
                        <a href="/home/case/<?php echo $p->id ?>" class="txt"><?php echo $p->name ?></a>
                        <div class="txt2">
                            <?php foreach ($p->category as $c) :?>
                                <a href="/home/list/<?php echo $c->id ?>"><?php echo $c->name ?></a>
                            <?php endforeach; ?>
                        </div>
                    </div>
                <?php endforeach; ?>

            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('#tab_2').addClass('selected');
    })
</script>