<style>
    h1 {
        font-size:24px;
    }
    .suuex {
        color:#aaa;
        font-size:14px;
        padding-bottom:20px;
        margin-bottom:20px;
        border-bottom:1px solid #E2E2E2;
    }
    .cont {
        line-height: 28px;
        font-size: 16px;
        color:#888;
    }
</style>
<div class="container breadc">
    <div class="cn" style="display: none">
        <div class="row">
            <div class="col-xs-12">
                <a href="/">首页</a>
                <span class="xsplt">/</span>
                <a href="/news/list">新闻动态</a>
                <span class="xsplt">/</span>
                <span class="xsexp"><?php echo $this->model->title ?></span>
            </div>
        </div>
    </div>
    <div class="en" style="display: none">
        <div class="row">
            <div class="col-xs-12">
                <a href="/?language=en">Home</a>
                <span class="xsplt">/</span>
                <a href="/news/list?language=en">News</a>
                <span class="xsplt">/</span>
                <span class="xsexp"><?php echo $this->model->title_en ?></span>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="cn" style="display: none">
            <div class="col-xs-12">
                <h1><?php echo $this->model->title ?></h1>
                <div class="suuex"><?php echo date_format($this->model->created_at, 'Y年m月d日')?></div>
                <div class="cont">
                    <div style="width: 100%; text-align: center; margin:20px 0;">
                        <img src="<?php echo $this->first_photo?>">
                    </div>
                    <?php echo $this->model->content ?>
                </div>
            </div>
        </div>
        <div class="en" style="display: none">
            <div class="col-xs-12">
                <h1><?php echo $this->model->title_en ?></h1>
                <div class="suuex"><?php echo date_format($this->model->created_at, 'm/d/Y')?></div>
                <div class="cont">
                    <div style="width: 100%; text-align: center; margin:20px 0;">
                        <img src="<?php echo $this->first_photo?>">
                    </div>
                    <?php echo $this->model->content_en ?>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="clear-50"></div>
<script type="text/javascript">
    $(document).ready(function() {
        $(".header").find(".selected").removeClass("selected");
        $(".header").find(".news").addClass("selected");
    });
</script>