<style>
    h1 {
        font-size:24px;
    }
    .suuex {
        color:#aaa;
        font-size:14px;
        padding-bottom:20px;
        margin-bottom:20px;
        border-bottom:1px solid #E2E2E2;
    }
    .cont {
        line-height: 28px;
        font-size: 16px;
        color:#888;
    }
</style>
<div class="container breadc">
    <div class="cn" style="display: none">
        <div class="row">
            <div class="col-xs-12">
                <a href="/">首页</a>
                <span class="xsplt">/</span>
                <a href="/about">公司简介</a>
            </div>
        </div>
    </div>
    <div class="en" style="display: none">
        <div class="row">
            <div class="col-xs-12">
                <a href="/">Home</a>
                <span class="xsplt">/</span>
                <a href="/about">Company Profile</a>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="cn" style="display: none">
        <div class="row">
            <div class="col-xs-12">
                <h1><?php echo $this->model[0]["title"] ?></h1>
                <div class="suuex"></div>
                <div class="cont">
                    <?php echo $this->model[0]["content"] ?>
                </div>
            </div>
        </div>
    </div>
    <div class="en" style="display: none">
        <div class="row">
            <div class="col-xs-12">
                <h1><?php echo $this->model[0]["title_en"] ?></h1>
                <div class="suuex"></div>
                <div class="cont">
                    <?php echo $this->model[0]["content_en"] ?>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="clear-50"></div>
<script type="text/javascript">
    $(document).ready(function() {
        $(".header").find(".selected").removeClass("selected");
        $(".header").find(".home").addClass("selected");
    });
</script>