<div id="content">
    <div id="title-text">
    </div>
    <div id="icon-container">
        <a href="http://se.360.cn/" target="_blank" id="bro-360" class="itm">
            <i></i>
            <p>360安全浏览器</p>
            <span id="jisumoshi"></span>
        </a>
        <a href="http://rj.baidu.com/soft/detail/14744.html?ald" target="_blank" id="bro-chrome" class="itm">
            <i></i>
            <p>谷歌Chrome</p>
        </a>
        <a href="http://rj.baidu.com/soft/detail/14917.html?ald" target="_blank" id="bro-ie" class="itm">
            <i></i>
            <p>IE 10 +</p>
        </a>
    </div>
    <div class="clear"></div>
    <div style="text-align:center;">
        <a href="/login" style="margin-top:70px;display:inline-block;border:3px solid #FFF; box-shadow: 0 2px 4px rgba(0,0,0,0.5);padding:5px 20px;color:#FFF;">已更换浏览器，进入芝士电视</a>
    </div>
</div>

<style>
    body {
        background:url(/img/upgrade-bg.jpg) center center fixed repeat #333 !important;
        font-family:"Microsoft Yahei";
    }

    #content {

    }
    #title-text {
        background:url(/img/upgrade-text.png) center center no-repeat;
        height:150px;
        width:1000px;
        margin:auto;
        margin-top:90px;
    }
    #icon-container {
        display:block;
        margin:auto;
        margin-top:50px;
        width:600px;
    }
    #icon-container .itm {
        display:inline-block;
        font-size:18px;
        float:left;
        text-align:center;
        text-shadow:0 1px 5px rgba(0,0,0,0.2);
        position:relative;
        width:200px;
    }
    #icon-container .itm:link {
        color:#FFF;
    }
    #icon-container .itm:visited {
        color:#FFF;
    }
    #icon-container .itm:hover {
        text-decoration: none;
        color:#FFF;
    }
    #icon-container .itm:hover i {
        background-position:left bottom;
    }
    
    #icon-container i {
        background:url(/img/upgrade-browser.png) left top no-repeat;
        display:block;
        height:150px;
        margin:auto;
        width:150px;
    }
    #bro-chrome i {
        background-position: center top;
    }
    #icon-container #bro-chrome:hover i {
        background-position:center bottom;
    }
    #bro-ie i {
        background-position: right top;
    }
    #icon-container #bro-ie:hover i {
        background-position:right bottom;
    }
    #icon-container .itm p {
        margin:20px 0 25px 0;
    }
    #jisumoshi {
        background:url(/img/jisumoshi.png) center center no-repeat;
        bottom:-20px;
        display:inline-block;
        left:50%;
        height:40px;
        margin-left:-55px;
        position:absolute;
        width:110px;
    }
</style>