<style>
</style>
<h1 class="page-title"><?php echo $this->title ?></h1>
<div class="row">
    <div class="col-md-8">
        <form role="form" method="post">
            <div class="form-group">
                <label>分类名称：</label>
                <input type="text" class="form-control" id="name" name="name" data-toggle="popover" value="<?php echo $this->model->name ?>">
            </div>
            <button type="submit" id="save-btn" class="btn btn-default">确认提交</button>
        </form>
    </div>
</div>
<script type="text/javascript">
    (function($) {
        $('#parent').setSelectValue();
        $('#save-btn').click(function() {
        });
    })(jQuery);
</script>