<style>
    .itm {
        padding:20px;
    }
    .itm:hover {
        background:#F0F0F0;
    }
    label.xs {
        color:#aaa;
        font-size:smaller;
        margin-left:5px;
    }
    .child-itm {
        border-left: 1px dotted #aaa;
        margin-top:10px;
        padding-left:30px;
    }
</style>

<h1 class="page-title"><?php echo $this->title ?></h1>
<div class="btb">
    <a id="clear-cache" class="btn btn-success" href="<?php echo $this->url(array(), 'manage-category-create') ?>">新建分类</a>
</div>
<div class="row">
    <?php
    $c = 0;
    ?>
    <?php if ($this->resource): ?>
        <?php foreach ($this->resource as $p): ?>
            <?php
//            $root = $p['root'];
//            $children = $p['children'];
            ?>
            <div class="col-md-2">
                <div class="itm">
                    <div class="paddingbox10px relative">
                        <p><?php echo $p->name ?></p>
                        <div class="btn-group">
                            <a type="button" href="<?php echo $this->url(array(id => $p->id), 'manage-category-save') ?>" class="btn btn-info btn-sm">编辑</a>
                            <?php if (!$this->productModel->getProductByCategory($p->id)): ?>
                                <button type="button" class="btn btn-danger btn-sm remove-category">删除</button>
                            <?php else: ?>
                                <label class="xs">被引用</label>
                            <?php endif; ?>

                        </div>

                        <input type="hidden" class="tmp" value="<?php echo $p->id ?>"/>
                    </div>
                </div>
            </div>
            <?php $c ++; ?>
            <?php if ($c % 6 == 0): ?>
                <div class="clearfix"></div>
            <?php endif; ?>
        <?php endforeach; ?>
    <?php endif; ?>
</div>
<script type="text/javascript">
    (function($) {
        $('.remove-category').click(function() {
            removeObject($(this), '<?php echo $this->url(array(), 'manage-category-remove') ?>');
        });
    })(jQuery);
</script>
