<style>
</style>
<h1 class="page-title"><?php echo $this->title ?></h1>
<div class="row">
    <div class="col-md-8">
        <form role="form" method="post">
            <div class="form-group">
                <label>电子邮箱1：</label>
                <input type="text" class="form-control" id="email1" name="email1" data-toggle="popover" value="<?php echo $this->model->email1 ?>">
            </div>
            <div class="form-group">
                <label>电子邮箱2：</label>
                <input type="text" class="form-control" id="email2" name="email2" data-toggle="popover" value="<?php echo $this->model->email2 ?>">
            </div>
            <div class="form-group">
                <label>公司地址：</label>
                <input type="text" class="form-control" id="company_address" name="company_address" data-toggle="popover" value="<?php echo $this->model->company_address ?>">
            </div>
            <div class="clear-20"></div>
            <button type="submit" id="save-btn" class="btn btn-default">确认提交</button>
        </form>
    </div>
</div>
<script type="text/javascript">
    (function($) {
        $('.gy-photo').photoSelector();

        $('#save-btn').click(function() {
            var save = $('#gy-photo').attr('save');
            if (!save || save === '{}') {
                $('#photo').val('');
            } else {
                $('#photo').val(save);
            }
        });

        $('#save-btn').click(function() {
            var save = $('#gy-photo').attr('save');
            if (!save || save === '{}') {
                $('#photo').val('');
            } else {
                $('#photo').val(save);
            }
        });

        $('input[name="programs[]"]').change(function(){
            $(this).closest('.label').toggleClass('label-success');
        });
    })(jQuery);
</script>