
<style>
</style>
<h1 class="page-title"><?php echo $this->title ?></h1>
<div class="row">
    <div class="col-md-8">
        <form role="form" method="post">
            <div class="form-group">
                <label>幻灯片图片：</label>
                <div class='panel panel-info'>
                    <div id="gy-photo" class='panel-body gy-photo'>
                    </div>
                </div>
                <input type="hidden" name="photo" id="photo"/>
            </div>
            <div  style="display: none"  class="form-group">
                <label>展示图文字：</label>
                <input type="text" class="form-control" id="remark" name="remark" data-toggle="popover" value="">
            </div>
            <!--英文部分-->
            <div style="display: none"  class="form-group">
                <label>展示图文字(英文)：</label>
                <input type="text" class="form-control" id="remark_en" name="remark_en" data-toggle="popover" value="">
            </div>
            <button type="submit" id="save-btn" class="btn btn-default">确认提交</button>
        </form>
    </div>
</div>
<script type="text/javascript">
    (function($) {
        $('.gy-photo').photoSelector();

        $('#save-btn').click(function() {
            var save = $('#gy-photo').attr('save');
            if (!save || save === '{}') {
                $('#photo').val('');
            } else {
                $('#photo').val(save);
            }
        });

        $('#save-btn').click(function() {
            var save = $('#gy-photo').attr('save');
            if (!save || save === '{}') {
                $('#photo').val('');
            } else {
                $('#photo').val(save);
            }
        });

        $('input[name="programs[]"]').change(function(){
            $(this).closest('.label').toggleClass('label-success');
        });
    })(jQuery);

    function left(id) {
        var own_programs = $('#gy-program').children();

        if ($(own_programs[0]).attr('id') == id) {
            return;
        }

        var cur_program = $('#'+ id);
        var lf_program = $(cur_program).prev('div');

        $(lf_program).remove();

        $(cur_program).after(lf_program);

        sortValue();
    }

    function right(id) {
        var own_programs = $('#gy-program').children();

        if ($(own_programs[own_programs.length - 1]).attr('id') == id) {
            return;
        }

        var cur_program = $('#'+ id);
        var rt_program = $(cur_program).next('div');

        $(rt_program).remove();

        $(cur_program).before(rt_program);

        sortValue();
    }

    function del(id) {
        var del_program = $('#'+ id);

        $(del_program).remove();

        var buttons = $(del_program).children('button');

        for (var i = 0; i < buttons.length; i++) {
            if ($(buttons[i]).html() != "O") {
                $(buttons[i]).hide();
            }
            else {
                $(buttons[i]).show();
            }
        }

        $(del_program).on("click", addProgram($(del_program).attr('id')));

        $('#not-program').append(del_program);

        sortValue();
    }

    function sortValue() {
        $('#programs').val("");

        var own_programs = $('#gy-program').children();

        for (var i = 0; i < own_programs.length;i++) {
            if ($('#programs').val() != "") {
                var val = $('#programs').val();

                $('#programs').val(val + ',');
            }

            var val = $('#programs').val();

            $('#programs').val(val + $(own_programs[i]).attr('id'));
        }
    }

    function addProgram(id) {
        var add_programs = $('#'+ id);

        var par_ele = $(add_programs).parent();

        if ($(par_ele).attr('id') == 'gy-program') {
            return;
        }

        var buttons = $(add_programs).children('button');

        for (var i = 0; i < buttons.length; i++) {
            if ($(buttons[i]).html() == "O") {
                $(buttons[i]).hide();
            }
            else {
                $(buttons[i]).show();
            }
        }

        $('#gy-program').append(add_programs);

        sortValue();
    }
</script>