<div class="row">
    <div class="col-md-4">
        <div class="intlbd">
            <h2>案例管理</h2>
            <p class="marginbottom10px"><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-case-list-home') ?>" role="button">查看所有案例 »</a></p>
            <p><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-case-create') ?>" role="button">添加案例 »</a></p>
        </div>
    </div>
    <div class="col-md-4">
        <div class="intlbd">
            <h2>分类管理</h2>
            <p class="marginbottom10px"><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-category-list-home') ?>" role="button">查看所有分类 »</a></p>
            <p><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-category-create') ?>" role="button">添加分类 »</a></p>
        </div>
    </div>
    <div class="col-md-4">
        <div class="intlbd">
            <h2>联系方式管理</h2>
            <p class="marginbottom10px"><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-contact-create') ?>" role="button">编辑联系方式 »</a></p>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <div class="intlbd">
            <h2>图片管理</h2>
            <p class="marginbottom10px"><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-photo-list-home') ?>" role="button">查看所有图片 »</a></p>
            <p><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-photo-upload') ?>" role="button">上传图片 »</a></p>
            <p><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-phototype-list-home') ?>" role="button">管理图片分类 »</a></p>
        </div>
    </div>
    <div class="col-md-4">
        <div class="intlbd">
            <h2>关于我们管理</h2>
            <p class="marginbottom10px"><a class="btn btn-default" href="<?php echo $this->url(array(), 'manage-about-create') ?>" role="button">编辑关于我们 »</a></p>
        </div>
    </div>
</div>
<style>
    .row {
        margin-bottom:30px;
    }
</style>
<script type="text/javascript">
    (function($) {

    })(jQuery);
</script>
