<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>关于我们 | VR设计</title>
    <link href="/css/bootstrap.css" rel="stylesheet">
    <link href="/css/iconfont.css" rel="stylesheet">
    <link href="/css/py_global.css" rel="stylesheet">
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="/js/jquery-bootstrap.js"></script>
    <script type="text/javascript" src="/js/py_global.js"></script>
</head>

<body>
<div class="xtopbne relative">
    <div class="container">
        <div class="row">
            <div class="col-xs-6">
                <img src="/img/logo.png" class="bglogo" />
            </div>
            <div class="col-xs-6">
                <ul class="big_menu">
                    <li onclick="location.href='/'">
                        <a href="/">HOME</a>
                    </li>
                    <li id="tab_2" onclick="location.href='/home/list'">
                        <a href="/home/list">CASE</a>
                    </li>
                    <li id="tab_3" onclick="location.href='/home/about'">
                        <a href="/home/about">ABOUT</a>
                    </li>
                    <li id="tab_4" onclick="location.href='/home/contact'">
                        <a href="/home/contact">CONTACT</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<?php echo $this->layout()->content; ?>
<div class="btban-wp">
    <div class="container">
        <div class="row">
            <div class="col-xs-10">
                <div class="btban-2">
                    <div class="tt">OPPORTUNITIES</div>
                    <span class="cti">Media</span>
                    <span class="cti">Join Us</span>
                    <span class="cti">Intership</span>
                    <span class="cti">Cooperation</span>
                </div>
                <div class="btban-2">
                    <div class="tt">SERVICES</div>
                    <span class="cti">Font Design</span>
                    <span class="cti">Brand Design</span>
                    <span class="cti">Layout Design</span>
                    <span class="cti">Visual Design</span>
                    <span class="cti">Graphic Design</span>
                    <span class="cti">Package Design</span>
                </div>
                <div class="btban-2">
                    <div class="tt">ABOUT</div>
                    <span class="cti">About Us</span>
                    <span class="cti">Pertners</span>
                    <span class="cti">Our Team</span>
                    <span class="cti">A Brief History</span>
                </div>
                <div class="btban-2">
                    <div class="tt">CONTACT</div>
                    <span class="cti">vr_design@163.com</span>
                    <span class="cti">147983574@qq.com</span>
                </div>
                <div class="btban-2">
                    <div class="tt">ADDRESS</div>
                    <span class="cti">ROOM 102.CTB Creative Factory. NO. 78 daxin Road.</span>
                    <span class="cti">Nanshan District. Shen-Zhen. Guangdong. China</span>
                </div>
                <div class="clear"></div>
            </div>
            <div class="col-xs-2">
                <div class="tt rf" style="font-weight:bold;margin-bottom:20px;">FOLLOW US</div>
                <div class="clear"></div>
                <div>
                    <a href="http://weibo.com/VRdesignhk" target="_blank" class="snsbtn"></a>
                                        <a href="javascript:void(0)" class="snsbtn weixin"></a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="showqrly"></div>
<script>
    $(document).ready(function() {
    });
</script>
</body>

</html>