<!DOCTYPE html>
<html>
    <head>
        <title>请升级浏览器 - 芝士电视</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link href="<?php echo $this->cssPath("bootstrap.css"); ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->cssPath("global.css"); ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->cssPath("global.show.css"); ?>" rel="stylesheet" type="text/css" />
        <script type="text/javascript" src="<?php echo $this->jsPath('jquery.1.10.2.min.js'); ?>"></script>
        <script type="text/javascript">
            $('document').ready(function() {
            });
        </script>
    </head>
    <body>
        <?php echo $this->layout()->content; ?>
    </body>
</html>



