<div id="tv-frame">
    <div class="board">
        <div class="title">
            <?php echo $this->title ?>
        </div>
        <div class="content">
            <form id="validate-form" method="post">
                <div class="bdrow">
                    <input type="password" placeholder="当前密码" id="password" name="password" data-toggle="popover" data-trigger ="manual" data-placement="right"/>
                </div>
                <div class="bdrow">
                    <input type="password" placeholder="新密码" id="new-password" name="new-password" data-toggle="popover" data-trigger ="manual" data-placement="right"/>
                </div>
                <div class="bdrow">
                    <input type="password" placeholder="再次输入密码" id="re-password" name="re-password" data-toggle="popover" data-trigger ="manual" data-placement="right"/>
                </div>

                <div class="bdrow">
                    <button type="submit" id="confirm-btn">确认修改</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">

<?php if ($this->reset): ?>
        $('.content').paper({type: 'success', additionalClass: 'sign-gotmsg'}, '<b class="glyphicon glyphicon-ok-sign"></b> 密码修改成功，请再次<a class="border-btn border-btn-xs" href="<?php echo $this->url(array(), 'login') ?>">登录芝士电视</a>');
<?php endif; ?>
<?php if ($this->error): ?>
        $('.content').paper({type: 'danger', additionalClass: 'sign-gotmsg'}, '<b class="glyphicon glyphicon-minus-sign"></b> <?php echo $this->error ?>');
<?php endif; ?>


    $("#validate-form").validate({
        rules: {
            "password": {
                required: true,
                minlength: 6
            },
            "new-password": {
                required: true,
                minlength: 6
            },
            "re-password": {
                equalTo: "#new-password"
            }
        },
        messages: {
        }
    });
</script>